import RootProvider from "@/core/providers/root-provider";
import { MenuToolbar, PageFooter } from "@/core/components";
import { Box, Container } from "@mui/material";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My commerce",
  description: "Generated by create next app",
};

const GLOBAL_LAYOUT_SX = {
  wrapper: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
  },
  container: {
    flex: 1,
    py: { xs: 2, md: 3 },
    px: { xs: 2, sm: 3, md: 4 },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={roboto.variable}>
      <body className={roboto.className}>
        <RootProvider>
          <Box sx={GLOBAL_LAYOUT_SX.wrapper}>
            <Container maxWidth="lg" sx={GLOBAL_LAYOUT_SX.container}>
              <MenuToolbar />
              {children}
            </Container>
            <PageFooter />
          </Box>
        </RootProvider>
      </body>
    </html>
  );
}
