import RootProvider from "@/core/providers/root-provider";
import MenuToolbar from "@/core/components/menu-toolbar";
import { Container } from "@mui/material";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My commerce",
  description: "Generated by create next app",
};

const GLOBAL_LAYOUT_SX = {
  container: {
    py: { xs: 2, md: 3 },
    px: { xs: 2, sm: 3, md: 4 },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={roboto.variable}>
      <body className={roboto.className}>
        <RootProvider>
          <Container maxWidth="lg" sx={GLOBAL_LAYOUT_SX.container}>
            <MenuToolbar />
            {children}
          </Container>
        </RootProvider>
      </body>
    </html>
  );
}
